using ExchangeRateApi.Models;
using ExchangeRateApi.Models.Responses;
using ExchangeRateApi.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

namespace ExchangeRateApi.Controllers {
    [Route("exchange_rate")]
    [ApiController]
    public class ExchangeRateController : ControllerBase {
        private readonly List<string> _services = new List<string>() { "OandaService", "GoogleService", "BloombergService" };
        private static Dictionary<string, CurrencyDictionaryModel> _cachedConversions = new Dictionary<string, CurrencyDictionaryModel>();
        private static int _timesCalled;

        [HttpGet]
        public async Task<ActionResult<double>> GetExchangeRate(string currencyCode, int amount) {
            if (!_validCodes.Contains(currencyCode) || amount == 0) return BadRequest("Currency Code is not a valid ISO 4217 code or amount is not valid");
            _timesCalled++;

            var information = string.Empty;
            if (_cachedConversions.ContainsKey(currencyCode) && _cachedConversions.GetValueOrDefault(currencyCode).Time.AddHours(6) > DateTime.Now) {
                var convertedAmount = _cachedConversions.GetValueOrDefault(currencyCode).ExchangeRate * amount;
                return convertedAmount;
            }

            foreach (var service in _services) {
                try {
                    Type type = Type.GetType($"ExchangeRateApi.Services.{service}");
                    Object obj = Activator.CreateInstance(type);
                    MethodInfo methodInfo = type.GetMethod("GetUSD");
                    Task<double> resultMethod =  (Task<double>) methodInfo.Invoke(obj, new object[] {currencyCode, amount});
                    var result = await resultMethod;

                    if (result == 0) throw new Exception($"{type.Name}: {methodInfo.Name} Failed");

                    information += $"{type.Name}: {methodInfo.Name} succeeded \n";
                    _cachedConversions.Remove(currencyCode);
                    var exchangeRate = result / amount;
                    var currencyDicModel = new CurrencyDictionaryModel(DateTime.Now, exchangeRate);
                    _cachedConversions.Add(currencyCode, currencyDicModel);
                    return result;
                }
                catch (Exception e) {
                    information += $"{e.Message} {e.InnerException} {e.StackTrace} ";
                }
            }
            return Problem(information);
        }

        [HttpGet("usage")]
        public int GetTotalUsage() {
            return _timesCalled;
        }

        //TODO: Add ability to convert to other codes other than usd

        private List<string> _validCodes = new List<string>() 
        {
           "AFN",
           "AFA",
           "ALL",
           "ALK",
           "DZD",
           "ADP",
           "AOA",
           "AOK",
           "AON",
           "AOR",
           "ARA",
           "ARS",
           "ARM",
           "ARP",
           "ARL",
           "AMD",
           "AWG",
           "AUD",
           "ATS",
           "AZN",
           "AZM",
           "BSD",
           "BHD",
           "BDT",
           "BBD",
           "BYN",
           "BYB",
           "BYR",
           "BEF",
           "BEC",
           "BEL",
           "BZD",
           "BMD",
           "BTN",
           "BOB",
           "BOL",
           "BOV",
           "BOP",
           "BAM",
           "BAD",
           "BAN",
           "BWP",
           "BRC",
           "BRZ",
           "BRE",
           "BRR",
           "BRN",
           "BRB",
           "BRL",
           "GBP",
           "BND",
           "BGL",
           "BGN",
           "BGO",
           "BGM",
           "BUK",
           "BIF",
           "XPF",
           "KHR",
           "CAD",
           "CVE",
           "KYD",
           "XAF",
           "CLE",
           "CLP",
           "CLF",
           "CNX",
           "CNY",
           "COP",
           "COU",
           "KMF",
           "CDF",
           "CRC",
           "HRD",
           "HRK",
           "CUC",
           "CUP",
           "CYP",
           "CZK",
           "CSK",
           "DKK",
           "DJF",
           "DOP",
           "NLG",
           "XCD",
           "DDM",
           "ECS",
           "ECV",
           "EGP",
           "GQE",
           "ERN",
           "EEK",
           "ETB",
           "EUR",
           "XEU",
           "FKP",
           "FJD",
           "FIM",
           "FRF",
           "XFO",
           "XFU",
           "GMD",
           "GEK",
           "GEL",
           "DEM",
           "GHS",
           "GHC",
           "GIP",
           "GRD",
           "GTQ",
           "GWP",
           "GNF",
           "GNS",
           "GYD",
           "HTG",
           "HNL",
           "HKD",
           "HUF",
           "ISK",
           "ISJ",
           "INR",
           "IDR",
           "IRR",
           "IQD",
           "IEP",
           "ILS",
           "ILP",
           "ILR",
           "ITL",
           "JMD",
           "JPY",
           "JOD",
           "KZT",
           "KES",
           "KWD",
           "KGS",
           "LAK",
           "LVL",
           "LVR",
           "LBP",
           "LSL",
           "LRD",
           "LYD",
           "LTL",
           "LTT",
           "LUL",
           "LUC",
           "LUF",
           "MOP",
           "MKD",
           "MKN",
           "MGA",
           "MGF",
           "MWK",
           "MYR",
           "MVR",
           "MVP",
           "MLF",
           "MTL",
           "MTP",
           "MRO",
           "MUR",
           "MXV",
           "MXN",
           "MXP",
           "MDC",
           "MDL",
           "MCF",
           "MNT",
           "MAD",
           "MAF",
           "MZE",
           "MZN",
           "MZM",
           "MMK",
           "NAD",
           "NPR",
           "ANG",
           "TWD",
           "NZD",
           "NIO",
           "NIC",
           "NGN",
           "KPW",
           "NOK",
           "OMR",
           "PKR",
           "PAB",
           "PGK",
           "PYG",
           "PEI",
           "PEN",
           "PES",
           "PHP",
           "PLN",
           "PLZ",
           "PTE",
           "GWE",
           "QAR",
           "XRE",
           "RHD",
           "RON",
           "ROL",
           "RUB",
           "RUR",
           "RWF",
           "SVC",
           "WST",
           "SAR",
           "RSD",
           "CSD",
           "SCR",
           "SLL",
           "SGD",
           "SKK",
           "SIT",
           "SBD",
           "SOS",
           "ZAR",
           "ZAL",
           "KRH",
           "KRW",
           "KRO",
           "SSP",
           "SUR",
           "ESP",
           "ESA",
           "ESB",
           "LKR",
           "SHP",
           "SDD",
           "SDG",
           "SDP",
           "SRD",
           "SRG",
           "SZL",
           "SEK",
           "CHF",
           "SYP",
           "STD",
           "TJR",
           "TJS",
           "TZS",
           "THB",
           "TPE",
           "TOP",
           "TTD",
           "TND",
           "TRY",
           "TRL",
           "TMT",
           "TMM",
           "USD",
           "USN",
           "USS",
           "UGX",
           "UGS",
           "UAH",
           "UAK",
           "AED",
           "UYU",
           "UYP",
           "UYI",
           "UZS",
           "VUV",
           "VEF",
           "VEB",
           "VND",
           "VNN",
           "CHE",
           "CHW",
           "XOF",
           "YDD",
           "YER",
           "YUN",
           "YUD",
           "YUM",
           "YUR",
           "ZRN",
           "ZRZ",
           "ZMW",
           "ZMK",
           "ZWD",
           "ZWR",
           "ZWL"
        };
    }

}
